services:
  - type: web
    name: vika-portfolio-bot
    runtime: python
    region: frankfurt
    buildCommand: pip install python-telegram-bot==20.0
    startCommand: python bot_simple.py
    envVars:
      - key: PORTFOLIO_TOKEN
        value: 8088348800:AAEgsVU7x1w-9FBr1gS9Xx74e_sVbYyBHzU